# Generated by Django 4.0.5 on 2022-07-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_blog', '0003_post_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-update_dt',)},
        ),
    ]
